### ISSUE TITLE
Problem with video

### ISSUE THREAD

**Issue by Machou** [doesdev/jquery-video-lightning#18]
Hello

With

this id : fjT2tJPGLFA don'twork
Error : "NetworkError: 404 Not Found - https://www.domain.com/fjT2tJPGLFA?"

this id: qyjCqJiRdow work

Why ? :/

**Comment by musocrat** [comment]
Hmm, that one may be tricky to troubleshoot. Here's what I get trying to get to that video. I can get to the one mentioned working.

![vid](https://cloud.githubusercontent.com/assets/1575051/13648431/90de31ae-e606-11e5-87bb-5076c83d0134.PNG)

**Comment by SMed79** [comment]
I've access to the video : http://i.imgur.com/ijqGJ04.png

**Comment by musocrat** [comment]
Try entering the video id in the [Youtube demo player](https://developers.google.com/youtube/youtube_player_demo)

In theory if it plays there it should work and we can troubleshoot from there. If not it is likely related to [this issue](https://code.google.com/p/gdata-issues/issues/detail?id=6267).

**Comment by SMed79** [comment]
Work http://i.imgur.com/zpFYRK1.png

**Comment by raullesteves** [comment]
Put -y at the beginning of the id
Example: y-VNpHMMa3NLM

**Comment by Machou** [comment]
Thanks @raullesteves but now i use [https://github.com/fancyapps/fancybox](Fancybox)
