### ISSUE TITLE
Works great with http, but NOT https

### ISSUE THREAD

**Issue by ShorePatrol** [doesdev/jquery-video-lightning#21]
I've added an SSL cert to my site, and it's now https://

Problem is, the video lightning no loner works...the link (which is really a SPAN) doesn't even show that it's a link anymore....?

How can this be fixed? Please help!

Thanks!

**Comment by ShorePatrol** [comment]
Ok - I updated:
<script src="http://code.jquery.com/jquery-latest.min.js"></script>

to
<script src="//code.jquery.com/jquery-latest.min.js"></script>

Now it works...

**Comment by doesdev** [comment]
Glad to hear that fixed it
