### ISSUE TITLE
Start time attribute ignored when lightbox closed and link clicked for second time

### ISSUE THREAD

**Issue by sbressler** [doesdev/jquery-video-lightning#23]
If you look at [this page](http://www.markblechner.com/mindbrain/music/) that's a work in progress, you'll see many links have start times embedded, like Musical Example #&#xfeff;3. However, if I click it, then click off the lightbox, then click it again, the start time is no longer respected. Is that expected behavior?

**Comment by doesdev** [comment]
Not expected, seems to be a bug. I'll try to take a look at it tomorrow and see if we can''t get that patched.

**Comment by sbressler** [comment]
Awesome, thanks for taking a look!

**Comment by sbressler** [comment]
Thank you for fixing so quickly! Deployed and confirmed it worked like a charm!
