### ISSUE TITLE
autopen

### ISSUE THREAD

**Issue by miloszmich** [doesdev/jquery-video-lightning#26]
It is possible to auto open after page loading?

**Comment by doesdev** [comment]
There isn't a built-in option for it, but you can control individual instances with JavaScript. They are stored in `window.vlData.instances` and can be started with the `play()`  and `stop()` methods.

For example, somewhere in your JS after they have been initialized and inside of a page load event you could do something like this `vlData.instances[1].play()` to trigger it opening.

I'm going to close this but feel free to ask anymore questions on it.
